name: Multiple triggers caller workflow

on:
  push: 
  workflow_dispatch:
    inputs:
      dispatchparam:
        default: 'a default value'
    overrides:
      workflowparam:
        value: ${{ vars.PLATFORMPROP }}
  
jobs:
  call-workflow:
    uses: mluzcabrera/enforceinputs/.github/workflows/real-workflow.yml@main
    with:
      who-to-greet: "Maria de la Luz"
